### ISSUE TITLE
Can't build

### ISSUE THREAD

**Issue by lucoceano** [jwyterlin/Reader#1]
Hey,

I'm trying to run your project in here but I've got 3 errors related to storyboard:
<img width="435" alt="screen shot 2015-07-03 at 10 06 22" src="https://cloud.githubusercontent.com/assets/1299301/8499630/30b2bba2-216b-11e5-9e45-6b4480293883.png">

Could you have a look and let me know?

Thanks

**Comment by jwyterlin** [comment]
Hi Lucas, sorry about that. I'm using the new XCode 7.0. I'll look into it and migrate back to Xcode 6.4 and this problem will be solved. The app still not complete, I'll continue it today.
